### DISCUSSION TITLE
Expand columns equal size

### DISCUSSION THREAD

**Discussion by BigfootN** [davatorium/rofi#1334] [Q&A]
Hello,

I'm trying to have the `listview` `elements` of equal size. Here is what I have so far come up with:

``` css
listview {
	layout: horizontal;
	scrollbar: false;
	children: [dummy, element, dummy2];
	position: center;
}

dummy {
	expand: true;
	position: west;
}

dummy2 {
	expand: true;
	position: east;
} 

element {
	text-color: #bdae93;
	expand: true;
	dynamic: true;
}
```

Unfortunately all the elements are positioned to the left of the window. I would like for all the elements to be of equal size.

Thank you very much in advance for any help.

**Comment by DaveDavenport** [comment]
Yeah, that is not a valid theme. listview does not have 'children' property.
What you want can easily be done (I think it is posted in some issue), but the important first question is what version of rofi do you run? it has changed a bit in the last releases.

**Reply by BigfootN** [reply]
Thank for your quick reply and sorry for my late answer.

The `rasi` config I presented was inspired by the [documentation](https://github.com/davatorium/rofi/blob/next/doc/rofi-theme.5.markdown#advanced-box-packing) in order to center the elements.

> I think it is posted in some issue

I indeed searched, but didn't find what I was looking for.

> what version of rofi do you run? 

The last one, version 1.6.1

> it has changed a bit in the last releases

What do you mean by that ?

Fortunately I figured it out (if this is the right way to do this) :

``` css
listview {
	enabled: true;
	cycle: true;
	scrollbar: false;
	columns: 4;
	lines: 1;
}
```

I just had to indicate the number of lines, and the number of columns, and it each element expanded (equal size).

Thank you very much in advance for your help.
