### DISCUSSION TITLE
[FileBrowser] Sorting by file modification time.

### DISCUSSION THREAD

**Discussion by TonCherAmi** [davatorium/rofi#1335] [Ideas/Feature Requests]
Hey, I'd like to add an option that would allow sorting files by modification time and I'm wondering how to best go about it:

- We could add a single option that only allows sorting by mtime (no atime or ctime):
   `-file-browser-sorting-method [by-name|by-modification-time]`
- Or we could do something similar to what `ls` does - there would be two options like:
  - `-file-browser-sorting-method [by-name|by-time]`
  - `-file-browser-sorting-time [mtime|atime|ctime]` (`mtime` being the default)

Personally I kind of like the second option better stylistically but at the same I'm not really sure whether it is going to be of any use to anyone and adding useless options should probably be avoided. What do you think?

**Comment by DaveDavenport** [comment]
i am not to sure on this one, (I prefer the 2nd), I could see this having added value (I would use it).

I also think we should not get to many options (working hard to reduce this), I had some plans to have something like this in config file to do more advanced tweaks:
```css
file-browser {
   sorting: mtime;
}
```

But this is not worked out yet.

**Reply by DaveDavenport** [reply]
A test of this is in one part of the code:
```css
combi {
  window: blue;
  drun: red;
}
```

Not a great working option.

**Reply by TonCherAmi** [reply]
> ```css
> file-browser {
>    sorting: mtime;
> }
> ```

This seems nice, though it looks like it would be difficult to distinguish between modi and widgets if it is done this way, maybe we could instead do something like:

```css
/*
or alternatively
configuration.mode.<mode>
mode.<mode> 
*/
configuration.<mode> {
  config-option: "value";
}
```

e.g

```css
/*
or alternatively
configuration.mode.file-browser
mode.file-browser 
*/
configuration.file-browser {
   sorting: mtime;
}
```

With this we should be able to collect the configuration values into a separate hash map and distribute them to their respective modes through the `rofi_mode` struct.

**Reply by DaveDavenport** [reply]
That is not a bad idea. 
Its time we get rid of the dual config system :D, current 
```css
configuration {
}
```
system is a bit of a hack.

**Reply by DaveDavenport** [reply]
maybe for this nesting is a bit better?

```css
configuration {
    drun {
         window: blue;
    }

}
```
