### DISCUSSION TITLE
[Themes] Can I make the prompt bold?

### DISCUSSION THREAD

**Discussion by adastx** [davatorium/rofi#1344] [Q&A] [answered]
prompt {
      text-color: @red;
      // can I make this bold?
    }

**Comment by DaveDavenport** [comment, marked as answer]
Select bold variant of font should work:
```css
prompt { font: "mono bold 12"; }
```
