### DISCUSSION TITLE
Centering the listview of rofi

### DISCUSSION THREAD

**Discussion by LamprosPitsillos** [davatorium/rofi#1363] [Q&A] [answered]
Can i have some help centering the list view please?
i tried 
`horizontal-align: 0.50;`
but nothing, i also tried location and anchor center...
I just want the text to be center aligned.
``` css
configuration {
  display-run: ":: ";
  display-drun: ":: ";
  display-window: ":: ";
  drun-display-format: "{name}";
  modi: "window,run,drun";
}

* {

  bg: #151515;
  bg-alt: #414141;

  fg: #ffffff;
  fg-alt: #f5f5f5;

  background-color: @bg;
  border-color: LightGrey;
  border: 0;
  margin: 0;
  padding: 1;
  spacing: 0;
}

element {
  padding: 12;
  orientation: vertical;
  text-color: @bg-alt;
  horizontal-align: 0.50;
}

element selected {
  text-color: @fg;
  horizontal-align: 0.50;
}

entry {
  padding: 12 0 12 3;
  text-color: @fg;
  font : "Fira Code Bold 14";
}

inputbar {
  children: [prompt, entry];
}

spacer {
	margin: 5 100 10 100;
	border: 0 0 2 0;
	border-color: @bg-alt; 
	padding: 0;
	expand: false;
}


listview {
  columns: 1;
  vertical-align: 0.50;
  location: center;
}


mainbox {
  children: [inputbar,spacer, listview];
}

prompt {
  padding: 12 0 0 12;
  text-color: #FFB52A ;
  font : "Fira Code Bold 14";
}

window {
  border: 1;
  transparency: "real";
}

```
here is my theme.
