### DISCUSSION TITLE
[REQUEST/QUESTION] Multiple keybinds for a action?

### DISCUSSION THREAD

**Discussion by Animeshz** [davatorium/rofi#1381] [Q&A] [answered]
I'd like to have toggle facility so `Alt+Space` opens and also closes it while `Esc` is still usable to close it. I tried passing `-kb-cancel Alt+space` but seems like that overrides the default `Esc` bind. Is it possible to have multiple keybinds for single operation?

**Comment by DaveDavenport** [comment, marked as answer]
Yes, you can bind multiple keys to one action comma separated. See `rofi -h` or `rofi -show keys` for examples (there are some in the default binding set).

```css
configuration {
	kb-primary-paste: "Control+V,Shift+Insert";
}
```
