### DISCUSSION TITLE
Fixing old pre-1.6.1 themes

### DISCUSSION THREAD

**Discussion by DaveDavenport** [davatorium/rofi#1398] [Theming] [answered]
In 1.6.1 we split the `element`  into `element-text` and `element-icon` (see 1.6.1 release notes).

To make an old theme work add the following section to the theme file:

```css
element-text {
    background-color: inherit;
    text-color:       inherit;
}
```

**Comment by DaveDavenport** [comment, marked as answer]
If you use icons, you might want to add:

```css
element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}
```

instead.
