### DISCUSSION TITLE
Unable to set lines and width

### DISCUSSION THREAD

**Discussion by Rubonnek** [davatorium/rofi#1407] [Theming] [answered]
Hello.

I just upgraded and I'm having issues upgrading to the new configuration format. For the most part, the Arc-Dark theme has what I want, but I'm unable to set number of lines and number of columns.

I tried setting the following:

```
configuration {
	font: "mono 9";
	location: 1;
	kb-row-tab: "";
	theme: "Arc-Dark";
	kb-row-select: "Tab";
}

listview {
	lines: 4;
	columns: 3;
}

window {
	width: 100%;
}
```

And here is the command I'm running `rofi` from through a keybind with `i3-wm`:
```
rofi -show run
```

The problem is that I want `rofi` to expand across my whole screen and have three columns. It's only covering half the screen and has one column:

![rofi](https://user-images.githubusercontent.com/8337880/131419616-e4554017-a801-46ca-bf46-984a4fcd68f1.png)

**Comment by DaveDavenport** [comment, marked as answer]
sorry, read 1/2.. (its late)

can you try this:

```css
configuration {
	font: "mono 9";
	location: 1;
	kb-row-tab: "";

	kb-row-select: "Tab";
}
@theme "Arc-Dark"
listview {
	lines: 4;
	columns: 3;
}

window {
	width: 100%;
}
```
