### DISCUSSION TITLE
Some settings does not respect the global properties section

### DISCUSSION THREAD

**Discussion by xlucn** [davatorium/rofi#1409] [Theming] [answered]
This is a MWE of config.rasi I worked out for the issue:
```css
* {
    margin           : 0;
    padding          : 0;
    border           : 0;
    spacing          : 0;
    text-color       : #EEFFFF;
    background-color : #212121;
}
```
I expect it to look like this:
![2021-08-31-175834_1440x592_scrot](https://user-images.githubusercontent.com/12032219/131483898-8066cb03-a323-4ad6-a5b6-5ec005e24a77.png)

But it actually looks like this:
![2021-08-31-175903_1440x604_scrot](https://user-images.githubusercontent.com/12032219/131483917-916f8c18-9cc7-4f65-8895-6fafac2b504d.png)

Items colors, window border, window padding does not use the settings in `*` section. Especially the border and padding, I expect them to apply anywhere. To make it looks like the first screenshot, I have to add the following in config.rasi:
```css
window {
    border          : 0px;
    padding         : 0px;
}

prompt, entry {
    text-color: @text-color;
}

element alternate normal, element normal normal {
    background-color: inherit;
    text-color: inherit;
}
```
I couldn't find in manual pages if there are some settings that are independent of global properties section, or can not be overridden by it.

Is there any documentation of this, and why do those settings behave like that?

**Comment by DaveDavenport** [comment, marked as answer]
can you please paste your complete raw config.rasi file?

**Reply by DaveDavenport** [reply]
It looks like you are loading the default theme, and then adding properties to it.

I see two solutions,  move your theme into a separate file and load that using
```css
@theme "mytheme"
```
or clear out the default theme, before your settings
````css
@theme "/dev/null"
* {
    margin           : 0;
    padding          : 0;
    border           : 0;
    spacing          : 0;
    text-color       : #EEFFFF;
    background-color : #212121;
}

window {
    border          : 0px;
    padding         : 0px;
}

prompt, entry {
    text-color: @text-color;
}

element alternate normal, element normal normal {
    background-color: inherit;
    text-color: inherit;
}
```
