### DISCUSSION TITLE
Change theme based on monitor size

### DISCUSSION THREAD

**Discussion by DaveDavenport** [davatorium/rofi#1410] [Theming]
Since 1.6.0 you can change your theme based on monitor size or ratio.
For example if you want on your full-hd monitor to go fullscreen, but not on the 4k monitor, you can add something like:

```css
@media (max-width: 1921 ) {
  window {
    fullscreen: true;
  }
}
```
