### DISCUSSION TITLE
ssh-launcher with terminator does not work

### DISCUSSION THREAD

**Discussion by akss13** [davatorium/rofi#1412] [Q&A] [answered]
I looked at issue [#982](https://github.com/davatorium/rofi/issues/982) where it was stated that the terminal emulator must support `-e` flag for ssh-launcher to work. I checked the terminator [manual](https://linux.die.net/man/1/terminator) and found terminator does support `-e` flag. I have set `terminal: "terminator";` in the config but it doesn't work.
Any tips on how to make it work?

**Comment by DaveDavenport** [comment, marked as answer]
It is annoying each terminal parses commandlines slightly different.
this should work for terminator:
```bash
rofi -show ssh -terminal "terminator"  -ssh-command '{terminal} -e "{ssh-client} {host} [-p {port}]"'
```

**Reply by DaveDavenport** [reply]
In config:
```css
configuration {                                                    
    terminal: "terminator";                                        
    ssh-command: "{terminal} -e '{ssh-client} {host} [-p {port}]'";
}                                                                  
```

terminator needs the -e argument quoted.
