### DISCUSSION TITLE
[BUG] Latest rofi breaks theme

### DISCUSSION THREAD

**Discussion by Morantoine** [davatorium/rofi#1436] [Theming]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/Morantxu/7ea956be81ee0741736c557849d91425

### Launch command

rofi -font 'Hack bold 14' -theme slate -combi-modi window#drun -show combi -modi combi

### Step to reproduce

* Launch rofi
* Look at the theme

### Expected behavior

The background of the text of the highlighted element is expected to be grey but it doesnt work on latest rofi version. Used to work fine before, I checked by downgrading the package.

### Actual behavior

![image](https://user-images.githubusercontent.com/71721545/132124935-944aa5d0-fd27-4e4c-9133-245d98a53b94.png)

**Comment by Bad3r** [comment]
There is a pinned issue with more information about themes breaking on rofi 1.7.0 (https://github.com/davatorium/rofi/issues/1397)

edit: check https://github.com/davatorium/rofi/issues/1427#issuecomment-913179583

**Comment by DaveDavenport** [comment]
I think the  the release notes and the hint in the pinned issue contains the fix.

**Comment by 0neGal** [comment]
I actually had a similar issue, and my only way to fix it was to use `-config` instead of `-theme` I have no clue why, whatsoever. For some reason it just overwrote whatever font and background color I'd made the elements with it's own.

So changing 
```sh
$ rofi -theme <theme>
```
to
```sh
$ rofi -config ~/.config/rofi/themes/<theme>.rasi
```

Obviously this means `config.rasi` doesn't get loaded, so don't have anything interesting in there. But for me I just had it `@import` my theme anyway.

**Reply by DaveDavenport** [reply]
no, please do not suggest to do that.  This is not the correct way to load a theme.

I will copy pasta this from several other posts:

In short:

`-config theme` theme is not a config, don't do this.

`-theme theme' discard all currently set theme settings and load this theme. This is for testing.

`configuration { theme: "theme" }` is an alias to the commandline option `-theme theme`. this should have been removed, but was overlooked, my apologies.

`@theme` discard all theme options and load new one.

`@import` appends to the current theme.

By default the default rofi theme is loaded. (`rofi -no-config -dump-theme to see it` )

To clear this you can either put your theme in separate file and load it with `@theme` or

use `@theme "/dev/null"`.

But I don't think this is relevant to the posters issue.

**Reply by DaveDavenport** [reply]
The above issue looks like the following needs to be added to the theme:

```css
element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}
```

**Reply by 0neGal** [reply]
My bad in that case! :)

**Reply by Bad3r** [reply]
> ...
> `configuration { theme: "theme" }` is an alias to the commandline option `-theme theme`. this should have been removed, but was overlooked, my apologies.
> 
> `@theme` discard all theme options and load new one.
> 
> `@import` appends to the current theme.
> 
> By default the default rofi theme is loaded. (`rofi -no-config -dump-theme to see it` )
> 
> To clear this you can either put your theme in separate file and load it with `@theme` or
> 
> use `@theme "/dev/null"`.

I am not sure if I get the correct syntax. Do you have an example config? 
Currently, this is my config file:

```yaml
configuration {
    theme: "themes/nord"; 
  timeout {
      action: "kb-cancel";
      delay:  0;
  }
  filebrowser {
      directories-first: true;
      sorting-method:    "name";
  }
}

```

I have tried to swap `theme: "themes/nord";` with `@theme "themes/nord";` or `@import "themes/nord";` both inside and outside the `configuration {}` scope. I keep receiving syntax errors when I do that.
![image](https://user-images.githubusercontent.com/25513724/132276476-846fe8c4-a792-42b9-85ba-73a48a63a394.png)

The theme I am using is  available here: [Nord theme](https://github.com/undiabler/nord-rofi-theme/blob/master/nord.rasi) by undiabler.

An example config might be helpful to avoid using the deprecated `theme: "theme` syntax.

I think the cause for the error is that there is a `configuration {}` block inside the theme file as well as inside the main config file

**Reply by DaveDavenport** [reply]
A configuration block does not belong inside a theme. That is indeed what that error is telling you.
A @theme/@import should always be outside of a block  'block {}'.

So (untested):

```css
configuration {

    display-ssh:    "";
    display-run:    "";
    display-drun:   "";
    display-window: "";
    display-combi:  "";
  timeout {
      action: "kb-cancel";
      delay:  0;
  }
  filebrowser {
      directories-first: true;
      sorting-method:    "name";
  }
}
@theme "themes/nord"

* listview {
lines: 6;
	columns: 2;
spacing: 10;
}
element {
children: [element-icon, element-text];
}
```

and remove the config block from the theme. (that seems very outdated).
