### DISCUSSION TITLE
Yet another "broken config with 1.7.0" post

### DISCUSSION THREAD

**Discussion by xfzv** [davatorium/rofi#1438] [Theming] [answered]
I'm sorry but I cannot figure how to fix my broken config to get it working with 1.7.0.

Adding 

```css
element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}
```

as suggested in the release notes doesn't work for me.

I tried moving my whole config to `~/.config/rofi/theme.rasi` and adding

```
@theme "theme"
```

to `~/.config/rofi/config.rasi` as suggested in https://github.com/davatorium/rofi/discussions/1430#discussioncomment-1282763, to no avail.

<details>
  <summary>My config</summary>

```css
configuration {
    modi: "drun";
    font: "JetBrainsMonoMedium Nerd Font 10.5";
    show-icons: true;
    icon-theme: "Papirus-Dark";
    display-drun: "   ";
    drun-display-format: "{icon} {name}";
    width: 40;
    lines: 8;
    columns: 1;
    location: 0;
    separator-style: "solid";
    hide-scrollbar: true;
}

* {
    highlight: bold italic;
    colorBackground:                #1e1e20;
    colorBackgroundSelected:        #282c34;
    colorForeground:                #c8ccd4;
    color01:                        #61afef;
    color02:                        #98c379;
    background-color:               @colorBackground;
    text-color:                     @colorForeground;
}

mainbox {
    padding: 5px;
    border: 3px;
    border-color: @color01;
}

listview {
    border: 2px;
    padding: 5px;
}

element {
    padding: 5px;
}

element-icon {
    size: 25px;
}

element selected {
    background-color: @colorBackgroundSelected;
    text-color: @color01;
}

element active {
    text-color: @color02;
}

element selected.active {
    text-color: @color02;
}

/* vim:ft=css
```

</details>

Any help is appreciated. Thanks!

**Comment by DaveDavenport** [comment, marked as answer]
No idea if this is correct as I don't know the correct situation:

```css
configuration {
    modi: "drun";
    font: "JetBrainsMonoMedium Nerd Font 10.5";
    show-icons: true;
    icon-theme: "Papirus-Dark";
    display-drun: "   ";
    drun-display-format: "{icon} {name}";
    width: 40;
    lines: 8;
    columns: 1;
    location: 0;
    separator-style: "solid";
    hide-scrollbar: true;
}
// clear the default theme.
@theme "/dev/null"

* {
    highlight: bold italic;
    colorBackground:                #1e1e20;
    colorBackgroundSelected:        #282c34;
    colorForeground:                #c8ccd4;
    color01:                        #61afef;
    color02:                        #98c379;
    background-color:               @colorBackground;
    text-color:                     @colorForeground;
}
window {
   width: 40%;
}
mainbox {
    padding: 5px;
    border: 3px;
    border-color: @color01;
}

listview {
    border: 2px;
    padding: 5px;
lines:  8;
columns: 1;
}

element {
    padding: 5px;
}

element-icon {
    size: 25px;
}

element selected {
    background-color: @colorBackgroundSelected;
    text-color: @color01;
}

element active {
    text-color: @color02;
}

element selected.active {
    text-color: @color02;
}
element-text, element-icon {
  vertical-align: 0.5;
  background-color: inherit;
  text-color: inherit;
}

/* vim:ft=css */
```
