### DISCUSSION TITLE
Unable to change element colors

### DISCUSSION THREAD

**Discussion by siduck** [davatorium/rofi#1453] [Theming] [answered]
Hi there , with the recent v1.7 update my rofi config has got messed up .

how do I add colors for element and element selected?

![2021-09-09-174024_1366x768_scrot](https://user-images.githubusercontent.com/59060246/132686161-2e98cecc-c28b-4a09-a50f-0eeb59a8beee.png)

my rofi config 

https://paste.sh/UhPs2ckJ#-9Zpgv1IA1Q5inCxddJ1SzoI

**Comment by DaveDavenport** [comment, marked as answer]
You are extending the default theme, to clear that out add:
```
@theme "/dev/null"
```
after your configuration {} block.

See also the other discussions in this forum.

**Reply by DaveDavenport** [reply]
you also want to add the tip from the sticky.

```css
element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}

```
