### DISCUSSION TITLE
[solved] Can someone help me fix my config/theme please?

### DISCUSSION THREAD

**Discussion by ecesar88** [davatorium/rofi#1491] [Theming] [answered]
Hello! I'm still very confused on how I should setup my config and theme file to make them work in this new version. I was thinking if someone could point out what I'm doing wrong.

Here is my config: http://ix.io/3ANX
And here is the theme: http://ix.io/3ANW

Weird thing is that if I pass ` -config <path to the config.rasi file>` I get this error: https://i.imgur.com/UfsMSeJ.png

But if I pass nothing, rofi starts but the theme gets all messed up: https://i.imgur.com/Ioaga8t.png

Thanks in advance!

**Comment by DaveDavenport** [comment, marked as answer]
that error you get is strange and does not match anything in the config file.

Can you give the full paths of your config files?

**Reply by ecesar88** [reply]
Sure. I had it bind to `$mod+d` on my i3 and bspwm config files:
`rofi --config ~/.config/rofi/config.rasi -show drun -theme ~/.config/rofi/onedark-pro.rasi`

I changed it to just `rofi -show drun` but then the theme gets messed up just as I showed before.

**Reply by DaveDavenport** [reply]
This works for me:
```css
configuration {
	modi: "run,drun,window";
	font: "Iosevka Bold 12";
	terminal: "alacritty";
       drun-display-format: "{icon} {name}";
       display-drun: " ";
       display-run: " ";
       display-window: " ";
}

@theme "onedark-pro"

element {
    children: [element-icon, element-text];
}

window {
  width:    1024px;
  y-offset: 180px;
  x-offset: 0px;
  padding:  5px;

  border: 8px;

  location: center;
  anchor:   center;
}

listview {
  lines: 8;
  columns: 2;
}

element-icon, element-text {
  background-color: inherit;  
  text-color: inherit;  
}
```

did not change the theme.
