### DISCUSSION TITLE
Remove the little + at the top right corner

### DISCUSSION THREAD

**Discussion by bonecountysheriff** [davatorium/rofi#1501] [Theming] [answered]
From the default config, how?

**Comment by DaveDavenport** [comment, marked as answer]
from the manpage:

```
   What does the icon in the top right show?
       The indicator shows:

              ` ` Case insensitive and no sorting.
              `-` Case sensitivity enabled, no sorting.
              `+` Case insensitive and Sorting enabled
              `±` Sorting and Case sensitivity enabled"
```

You can remove this indicator widget in your theme, see rofi-theme manpage.
You can remove it from the children on the input bar:

Add this to the end of your config.rasi:

```css
inputbar {
     children:   [ prompt,textbox-prompt-colon,entry,num-filtered-rows,textbox-num-sep,num-rows ];
}
```


(it kinda depends on the theme used, but this might work.)
