### DISCUSSION TITLE
Change the color of "/" in "num-filtered-rows / num-rows"

### DISCUSSION THREAD

**Discussion by bonecountysheriff** [davatorium/rofi#1503] [Theming] [answered]
I was able to change the colors of everything else in the inputbar. 

How do you do this?

**Comment by DaveDavenport** [comment, marked as answer]
Please post theme questions in the theme category (I moved it )

```css
textbox-num-sep{
text-color: pink;
}
```
