### DISCUSSION TITLE
Strange white square in icons in ROFI.

### DISCUSSION THREAD

**Discussion by DARKBOW923** [davatorium/rofi#1506] [Theming]
As the title says, i updated my system (gentoo), and now when i open rofi i have white squares in the icons.

![image](https://user-images.githubusercontent.com/59940188/137730239-81d28ce1-34c1-4d58-8551-fe48d721fd51.png)
Any help? ty.

**Comment by DaveDavenport** [comment]
please see the other discussion in this forum, this one has been mentioned many times.
I think the 'fix' mentioned int he pinned issue is the fix for this:
https://github.com/davatorium/rofi/issues/1397

append to theme:
```css
element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}

```

**Reply by DaveDavenport** [reply]
looking at the image, you are also hitting a icon alignment bug (will be fixed in 1.7.1)
```css
element-icon {
vertical-align: 0.5;
horizontal-align: 0.5;
}
```
