### DISCUSSION TITLE
Remove the little - at the top bellow input bar

### DISCUSSION THREAD

**Discussion by xealea** [davatorium/rofi#1522] [Theming] [answered]
[![2021-11-14-09-59-48-screenshot.png](https://i.postimg.cc/W3LZ7TKn/2021-11-14-09-59-48-screenshot.png)](https://postimg.cc/PLyNXsdp)

hello sir i have some problem with my rofi configuration, i want to remove seperator in the bellow input bar but i don't know how to remove them. after rofi change to 1.7.0 i'm a bit confused because many configurations have been changed

**Comment by DaveDavenport** [comment, marked as answer]
dotted border is part of the theme, but was broken < 1.7.0, the fix made it show correctly in the theme again.

Pasting your theme might help.

Not to much changed, but stuff that had been deprecated for years has been removed.

**Reply by xealea** [reply]
oh means this is an old feature which was fixed and now it appears. so basically the dotted border below cannot be removed (default) sir

**Reply by DaveDavenport** [reply]
it can be removed. 

Pasting your theme might help.

**Reply by xealea** [reply]
```rasi
configuration {
    show-icons:                     true;
    display-drun: 					"applications";
    drun-display-format:            "{icon} {name}";
    disable-history:                false;
	click-to-exit: 					true;
    location:                       center;
    font:				 	        "Noto Sans 10";
}

@import "colors.rasi"

window {
    background-color:               @BG;
    border:                  		0px;
    border-color:                  	@BGA;
    border-radius:                  10px;
    width:                          600px;
    height:                         400px;
    x-offset:                       0px;
    y-offset:                       125px;
}

prompt {
    enabled: 			    true;
    margin: 		            0px 0px 0px 8px;
    padding: 			    8px;
    background-color: 		    @BGA;
    text-color: 		    @FG;
    border:                  	    1px 1px 1px 1px;
    border-color:                   @BDR;
    border-radius:                  6px;
}

textbox-prompt-colon {
    expand: 		            false;
    str: 			    "";
    border-radius:                  6px;
    background-color:               @SEL;
    text-color:                     @BGA;
    padding:                        8px 12px 8px 12px;
    font:			    "Noto Sans 10";
}

entry {
    background-color:               @BGA;
    text-color:                     @FG;
    placeholder-color:              @FG;
    expand:                         true;
    horizontal-align:               0;
    placeholder:                    "Search...";
    blink:                          true;
    border:                  		0px 0px 2px 0px;
    border-color:                  	@BDR;
    border-radius:                  10px;
    padding:                        8px;
}

inputbar {
    children: 			            [ textbox-prompt-colon,prompt ];
    background-color:               #00000000;
    text-color:                     @FG;
    expand:                         false;
    border:                  	    0px 0px 0px 0px;
    border-radius:                  0px;
    border-color:                   @BDR;
    margin:                         0px 0px 0px 0px;
    padding:                        0px;
    position:                       center;
}

case-indicator {
    background-color:               @BG;
    text-color:                     @FG;
    spacing:                        0;
}

listview {
    background-color:               #00000000;
    columns:                        2;
    lines:			    8;
    spacing:                        5px;
    cycle:                          false;
    dynamic:                        true;
    layout:                         vertical;
    scrollbar:                      false;
}

mainbox {
    background-color:               rgba(0,0,0,0);
    children:                       [ inputbar, listview ];
    spacing:                        15px;
    padding:                        30px;
}

element {
    background-color:   rgba(0,0,0,0);
    padding:	5px;
    border-radius:	8px;
}
element-icon {
    background-color:               inherit;
    text-color:                     inherit;
    horizontal-align:               0.5;
    vertical-align:                 0.5;
    size:                           20px;
    border:                         0px;
}
element-text {
    background-color:               inherit;
    text-color:                     inherit;
    expand:                         true;
    horizontal-align:               0;
    vertical-align:                 0;
    margin:                         2px 0px 2px 2px;
}
element.normal.normal {
    background-color: @UGT;
    text-color:       @FG;
}
element.normal.urgent {
    background-color: @UGT;
    text-color:       @BGA;
}
element.normal.active {
    background-color: @UGT;
    text-color:       @BGA;
}
element.selected.normal {
    background-color: @SEL;
    text-color:       @BGA;
}
element.selected.urgent {
    background-color: @UGT;
    text-color:       @BGA;
}
element.selected.active {
    background-color: @BG;
    text-color:       @FG;
}
element.alternate.normal {
    background-color: @BG;
    text-color:       @FG;
}
element.alternate.urgent {
    background-color: @BG;
    text-color:       @FG;
}
element.alternate.active {
    background-color: @BG;
    text-color:       @FG;
}
```

**Reply by xealea** [reply]
Here my configuration theme sir @DaveDavenport

**Reply by DaveDavenport** [reply]
the current setup extends the default theme, that has the dotted line. Put this:

```css


@import "colors.rasi"

window {
    background-color:               @BG;
    border:                  		0px;
    border-color:                  	@BGA;
    border-radius:                  10px;
    width:                          600px;
    height:                         400px;
    x-offset:                       0px;
    y-offset:                       125px;
}

prompt {
    enabled: 			    true;
    margin: 		            0px 0px 0px 8px;
    padding: 			    8px;
    background-color: 		    @BGA;
    text-color: 		    @FG;
    border:                  	    1px 1px 1px 1px;
    border-color:                   @BDR;
    border-radius:                  6px;
}

textbox-prompt-colon {
    expand: 		            false;
    str: 			    "";
    border-radius:                  6px;
    background-color:               @SEL;
    text-color:                     @BGA;
    padding:                        8px 12px 8px 12px;
    font:			    "Noto Sans 10";
}

entry {
    background-color:               @BGA;
    text-color:                     @FG;
    placeholder-color:              @FG;
    expand:                         true;
    horizontal-align:               0;
    placeholder:                    "Search...";
    blink:                          true;
    border:                  		0px 0px 2px 0px;
    border-color:                  	@BDR;
    border-radius:                  10px;
    padding:                        8px;
}

inputbar {
    children: 			            [ textbox-prompt-colon,prompt ];
    background-color:               #00000000;
    text-color:                     @FG;
    expand:                         false;
    border:                  	    0px 0px 0px 0px;
    border-radius:                  0px;
    border-color:                   @BDR;
    margin:                         0px 0px 0px 0px;
    padding:                        0px;
    position:                       center;
}

case-indicator {
    background-color:               @BG;
    text-color:                     @FG;
    spacing:                        0;
}

listview {
    background-color:               #00000000;
    columns:                        2;
    lines:			    8;
    spacing:                        5px;
    cycle:                          false;
    dynamic:                        true;
    layout:                         vertical;
    scrollbar:                      false;
}

mainbox {
    background-color:               rgba(0,0,0,0);
    children:                       [ inputbar, listview ];
    spacing:                        15px;
    padding:                        30px;
}

element {
    background-color:   rgba(0,0,0,0);
    padding:	5px;
    border-radius:	8px;
}
element-icon {
    background-color:               inherit;
    text-color:                     inherit;
    horizontal-align:               0.5;
    vertical-align:                 0.5;
    size:                           20px;
    border:                         0px;
}
element-text {
    background-color:               inherit;
    text-color:                     inherit;
    expand:                         true;
    horizontal-align:               0;
    vertical-align:                 0;
    margin:                         2px 0px 2px 2px;
}
element.normal.normal {
    background-color: @UGT;
    text-color:       @FG;
}
element.normal.urgent {
    background-color: @UGT;
    text-color:       @BGA;
}
element.normal.active {
    background-color: @UGT;
    text-color:       @BGA;
}
element.selected.normal {
    background-color: @SEL;
    text-color:       @BGA;
}
element.selected.urgent {
    background-color: @UGT;
    text-color:       @BGA;
}
element.selected.active {
    background-color: @BG;
    text-color:       @FG;
}
element.alternate.normal {
    background-color: @BG;
    text-color:       @FG;
}
element.alternate.urgent {
    background-color: @BG;
    text-color:       @FG;
}
element.alternate.active {
    background-color: @BG;
    text-color:       @FG;
}
```
in mytheme.rasi 
and replace the theme bits in your config.rasi with :

```
@theme "mytheme"
```
