### DISCUSSION TITLE
Selected items are not displayed correctly (Rofi + pywal)

### DISCUSSION THREAD

**Discussion by d4rios** [davatorium/rofi#1580] [Theming]
When launching rofi with the template generated by pywal I can't see the selected items. When I scroll up and down with the arrow keys they are produced as jumps.

If I enter the name of a program or application I don't see the match of the application I am going to launch. I can only confirm the application when I press the enter key and it is opened.

This behavior happens with both the dark and light pywal theme.

I am not clear if it's pywal's or rofi's problem.

I attach a video where you can see and understand better what I am trying to say.

I hope you can help me with this.

Thank you very much.

https://drive.google.com/file/d/1Y5x8MR9jt2Lsc1Ae0m6bgcsFwmX0zpc0/view?usp=sharing

**Comment by DaveDavenport** [comment]
it looks like pywal is generating an invalid theme for the version of rofi you are running.

can you paste some information?   rofi version, configuration, theme.

**Comment by d4rios** [comment]
Of course!!.

### rofi ### 
rofi -v
Version: 1.7.3

### python-pywal ### 
wal -v
wal 3.3.0


### launcher.rasi ### 
```css
configuration {
    location: 						0;
    fixed-num-lines: 				        true;
    show-icons: 					false;
    sidebar-mode: 					true;
    scroll-method: 					1;
    window-format: 					"[{w}] ··· {c} ···   {t}";
    click-to-exit: 					true;
    combi-hide-mode-prefix: 		        false;
    display-window: 				        "";
    display-windowcd: 				"";
    display-run: 					"";
    display-ssh: 					"";
    display-drun: 					"";
    display-combi: 					"";
}

/* Dark theme. */
@import "~/.cache/wal/colors-rofi-dark"

* {
    font:                                      "Iosevka 10";
    background-color:             	@background;
}

window {
    border: 						1px;
    border-color: 					@selected;
    border-radius: 					0px;
    width: 							500px;
    height: 						0px;
}

prompt {
    spacing: 					0;
    border: 					0;
    background-color:             	        @highlight;
    text-color: 					@background;
    padding:    					6px 10px 6px 10px;
}

textbox-prompt-colon {
    expand: 					false;
    str: 						"";
    padding:    					6px 4px 6px 4px;
    text-color: 					inherit;
}

entry {
    spacing:    					0;
    expand:                                       true;
    horizontal-align:                           0;
    text-color: 					@foreground;
    placeholder-color:                       @FG;
    placeholder:                                "Buscar...";
    padding:    					6px 2px 6px 2px;
    border: 					0px 0px 1px 0px;
    border-color: 				@selected;
    border-radius: 				0px;
}

case-indicator {
    spacing:    					0;
    text-color: 					@foreground;
}

inputbar {
    spacing:    					0px;
    text-color: 					@foreground;
    border: 					0px;
    border-color: 				@selected;
    border-radius: 				0px;
    children: 					[ prompt,textbox-prompt-colon,entry ];
}

mainbox {
    border: 						0px;
    border-color: 					@selected;
    spacing: 						6px;
    padding: 						10px;
}

listview {
    lines:							7;
    columns:						1;
    fixed-height: 					0;
    border: 						0px;
    border-color: 					@foreground;
    spacing: 						2px;
    scrollbar: 						false;
    padding: 						4px 0px 0px;
}

element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}

element {
    border: 						0px;
    padding: 						7px;
}
element normal.normal {
    background-color: 			@background;
    text-color:       				@foreground;
}
element normal.urgent {
    background-color: 			@background;
    text-color:       				@off;
}
element normal.active {
    background-color: 			@background;
    text-color:       				@on;
}
element selected.normal {
    background-color: 			@selected;
    text-color:       				@background;
    border: 					0px;
    border-color: 				@selected;
}
element selected.urgent {
    background-color: 			@background;
    text-color:       				@off;
}
element selected.active {
    background-color: 			@background;
    text-color:       				@selected;
}
element alternate.normal {
    background-color: 			@background;
    text-color:       				@foreground;
}
element alternate.urgent {
    background-color: 			@background;
    text-color:       				@foreground;
}
element alternate.active {
    background-color: 			@background;
    text-color:       				@foreground;
}

sidebar {
    border:       					0px;
    border-color: 				@selected;
    border-radius: 				0px;
}

button {
    margin: 					5px 0px 0px 0px;
    horizontal-align:                           0.5;
    vertical-align:                               0.5;
    padding: 					7px;
    text-color: 					@foreground;
    border: 					0px;
    border-radius: 				0px;
    border-color: 				@selected;
}

button selected {
    background-color:             	        @selected;
    text-color: 					@background;
    border: 					0px;
    border-radius: 				0px;
    border-color: 				@selected;
}

scrollbar {
    width:        					4px;
    border:       					0px;
    handle-color: 				@foreground;
    handle-width: 				8px;
    padding:      				0;
}

message {
    border: 					0px;
    border-color: 				@selected;
    padding: 					1px;
}

textbox {
    text-color: 					@foreground;
}
```

The themes are "~/.cache/wal/colors-rofi-dark" and "~/.cache/wal/colors-rofi-light".

The same thing happened with earlier versions of rofi.
