### DISCUSSION TITLE
Items aren't being displayed

### DISCUSSION THREAD

**Discussion by ndavd** [davatorium/rofi#1589] [Theming] [answered]
Hi, I noticed that on the latest version rofi items were no longer being displayed... I can't figure out what has changed.
[This](https://github.com/ndavd/dotfiles/blob/main/.config/rofi/themes/wopr.rasi) is the custom theme I'm using. Thanks.

**Comment by DaveDavenport** [comment, marked as answer]
Interesting, can you also pastebin your config?

**Reply by DaveDavenport** [reply]
What is your current version and the version it still worked?

**Reply by DaveDavenport** [reply]
Removing the hardcoded height fixes the theme, the hardcoded size is not enough to show the elements.

**Reply by DaveDavenport** [reply]
```css
/***
* ROFI Color theme
* NAME: wopr.rasi
* AUTHOR: ndavid
***/

* {
  /* THESE COLORS ARE CHANGED WITH chtheme */
  COLOR1:              #aa0000;
  COLOR2:              #161616;
  COLOR3:              #000000;

  font:                "Monospace 8.8";
height:              1.2em;
                     text-color:          #fff;
  background-color:    @COLOR3;
  element-background:  @COLOR2;
  selected-background: @COLOR1;
}
window {
  anchor: north;
  location: north;
  width: 100%;
  padding: 0px;
  children: [ horibox ];
}
horibox {
  orientation: horizontal;
  children: [ prompt, entry, listview ];
}
prompt {
  padding: 0 1ch;
  background-color: @selected-background;
}
listview {
  layout: horizontal;
  lines: 100;
}
entry {
  expand: false;
  padding: 0 2px;
  width: 10em;
  blink: false;
}
element {
  padding: 0 1ch;
  background-color: @element-background;
  children: [ element-icon, element-text];
}
element.selected {
  background-color: @selected-background;
}
element-text {
  background-color: inherit;
  text-color: inherit;
}
element-icon {
  size: 1em;
  background-color: inherit;
}
```
