### DISCUSSION TITLE
Showing icons only on drun

### DISCUSSION THREAD

**Discussion by pta2002** [davatorium/rofi#1811] [Theming] [answered]
I'm trying to make a custom theme for rofi, and I only want to show icons on the `drun` mode. Is there any way to do this other than duplicating the theme and making one with and without that?

**Comment by DaveDavenport** [comment, marked as answer]
No, themes are separate from modes.

You don't need to duplicate the theme, you can use an  import  to load theme and then override the settings.

```css
@import "my-fancy-theme-with-icons"

element {
   children: [ element-text ];
}
```

Or use a an environment variable to change the theme (https://davatorium.github.io/rofi/guides/DynamicThemes/dynamic_themes/)
