### DISCUSSION TITLE
Set Line Number and Line Padding

### DISCUSSION THREAD

**Discussion by blueray453** [davatorium/rofi#1859] [Q&A] [answered]
Earlier i had the following two lines in `config.rasi`:

```
line-padding: 5;
lines: 40;
```
It does not seem to be working after updating to Version: 1.7.5 I think the old ways have changed. How can I set this in the new config file.

**Comment by DaveDavenport** [comment, marked as answer]
See https://davatorium.github.io/rofi/1.7.5/rofi-theme.5/

For padding on the line:

```css
element {
padding: 5px;
}
```
For spacing between lines:
```css
listview {
spacing: 5px;
lines: 40;
}
```
