### DISCUSSION TITLE
What is the configuration setting to hide listview ?

### DISCUSSION THREAD

**Discussion by ABelliqueux** [davatorium/rofi#1878] [Q&A] [answered]
I see here ; https://github.com/davatorium/rofi/issues/1079 
and there ; https://github.com/davatorium/rofi/pull/1622

that there's now a setting to disable listview on launch. The discussion and PR description both fail to mention that new setting's syntax. 

Can anyone tell me what I should put in my config file ?

Thanks !

**Comment by DaveDavenport** [comment]
From the documentation, its the require-input flag:

```css
listview {
    require-input: true;
}
```
This is also what is proposed in #1079.

**Comment by ABelliqueux** [comment]
Thanks for your reply. 
So I tried putting that into my `config.rasi` file, i.e :  
```css
configuration {
  modes: "run";
  timeout {
      action: "kb-cancel";
      delay:  0;
  }
  filebrowser {
      directories-first: true;
      sorting-method:    "name";
  }
  listview {
    require-input: true;
  }

}
@theme "/usr/share/rofi/themes/Monokai.rasi"

```

but I'm still seeing a list of executables under the "run" prompt when launching rofi.
I tried screenshoting rofi, but couldn't find how to do that without the prompt disappearing...

Is this how I'm supposed to use this setting ?

FWIW, I'm trying to replicate the look of gmrun ; 

![gmrun](https://github.com/davatorium/rofi/assets/1405255/dc0e5941-3af0-4ac8-b573-6d1ebcec9615)

Thanks for taking the time to answer !

**Reply by DaveDavenport** [reply, marked as answer]
```css
configuration {
  modes: "run";
  timeout {
      action: "kb-cancel";
      delay:  0;
  }
  filebrowser {
      directories-first: true;
      sorting-method:    "name";
  }


}
@theme "/usr/share/rofi/themes/Monokai.rasi"
  listview {
    require-input: true;
  }
```
