### DISCUSSION TITLE
How do I make the box on the right and the separator between the inputbar and the listview disappear?

### DISCUSSION THREAD

**Discussion by Leo-DaVinki** [davatorium/rofi#1879] [Q&A]
![rofi](https://github.com/davatorium/rofi/assets/107254731/b2c259ed-3011-457a-8224-922bb7e4a56e)
Here is my theme. It is a simple theme with two colors which I intend to change depending on my system colors at the time:

```css
* {
    fg: #e0dcd4;
    bg: #160f06;
border: 0px;
}
window {
	background-color: @bg;
	border: 0;
	padding: 0;
}
element.normal.normal {
    background-color: @bg;
    text-color:       @fg;
}
element.normal.urgent {
    background-color: @bg;
    text-color:       @fg;
}
element.normal.active {
    background-color: @bg;
    text-color:       @fg;
}
element.selected.normal {
    background-color: @fg;
    text-color:       @bg;
}

element.selected.urgent {
    background-color: @fg;
    text-color:       @bg;
}
element.selected.active {
    background-color: @fg;
    text-color:       @bg;
}
element.alternate.normal {
    background-color: @bg;
    text-color:       @fg;
}
element.alternate.urgent {
    background-color: @bg;
    text-color:       @fg;
}
element.alternate.active {
    background-color: @bg;
    text-color:       @fg;
}
scrollbar {
    width:        4px ;
    border:       0;
    handle-width: 8px ;
    padding:      0;
    handle-color: @fg;
    background-color: @bg;
}
element-text {
 background-color: inherit;
 text-color: inherit;
}
textbox {
text-color: @fg;
background-color: @bg;
}
listview {
    fixed-height: 0;
    border:       0px 0px 0px ;
    spacing:      0px ;
    scrollbar:    true;
    padding:      0px 0px 0px ;
background-color: @bg;
lines: 10;
layout: vertical;
}
prompt {
    spacing:    0;
    text-color: @fg;
background-color: @bg;
str: "test: ";
border: 0px 0px 0px 0px;
}
inputbar {
background-color: @bg;
text-color: @fg;
border: 0px;
}
entry {
spacing: 0;
background-color: @bg;
text-color: @fg;
}

```
edit; fix code block.

**Comment by DaveDavenport** [comment]
I think:

```css
mainbox { 
    spacing: 0px;
}
```

```css
inputbar {
    children: [ prompt, entry ];
}
```
