### DISCUSSION TITLE
Is it possible to pass a data to a specific children element?

### DISCUSSION THREAD

**Discussion by HoloTWW** [davatorium/rofi#2017] [Q&A]
Hello everyone. I really new to Rofi. There is an interesting example in the documentation (`rofi-theme.5`):
``` css
element {
  orientation: horizontal;
  children: [ element-text, element-icon ];
  spacing: 5px;
}
```

```text
┌─────────────────────────────────────────────────────────────────────┐ 
│ element                                                             │ 
│ ┌─────────────────────────────────────────────┐ ┌─────────────────┐ │ 
│ │element─text                                 │ │ element─icon    │ │ 
│ └─────────────────────────────────────────────┘ └─────────────────┘ │ 
└─────────────────────────────────────────────────────────────────────┘ 
```

The question is - can we make something like this (and insert for each element-text its own listview):
``` css
element {
  orientation: horizontal;
  children: [ element-text, element-text ];
  spacing: 5px;
}
```

```text
┌─────────────────────────────────────────────────────────────────────┐ 
│ element                                                             │ 
│ ┌─────────────────────────────────────────────┐ ┌─────────────────┐ │ 
│ │element─text                                 │ │ element─text     │ │ 
│ └─────────────────────────────────────────────┘ └─────────────────┘ │ 
└─────────────────────────────────────────────────────────────────────┘ 
```

In my head the solution looks something like this, but I don’t know how to access a specific element to pass data to it correctly (if  is it even possible):

``` bash
list1=(1 2 3)
list2=(x y z)
printf "%s\n" "${list1[@]}" "${list2[@]}" | rofi -dmenu -config ./myconfig.rasi)
```
