### DISCUSSION TITLE
Help with dotted line at top of listview.

### DISCUSSION THREAD

**Discussion by jwnome** [davatorium/rofi#2035] [Theming]
![image](https://github.com/user-attachments/assets/ba5b5149-9831-4f50-a0cd-2d30f3145c42)

I'm trying to get rid of this dotted line.
I'm not using any theme, I have edited the config file and just looking for Rofi to use that.

There was another person with the same issue and the only thing you appeared to change was adding an @import: colors.rasi file, but I don't have an additional colors or theme file, but I believe it's the extending of the default theme as you mentioned in the other post.
I have tried loading the blank dev/null theme, this completely breaks my config, and I have tried several variations of loading mytheme, but same result.

What am I missing?

Here is my config file:

configuration {
    modi: "drun";
    show-icons: false;
    font: "JetBrains Mono 16";
    sort: true;
}

window {
    transparency: "real";
    width: 2560px;
    background-color: #0D1117CC;
    border-radius: 10px;
    border-color: #0D1117CC;
    padding: 780px;
}

listview {
    columns: 1;
    lines: 4;
    fixed-height: true;
    cycle: false;
    scrollbar: false;
    spacing: 0px;
}

prompt {
    text-color: #FEB4CBFF;
}

inputbar {
    children: ["prompt", "entry"];
    spacing: 8px;
    horizontal-align: 0.5;
}

entry {
    placeholder: "";
    text-color: #FEB4CBFF;
    placeholder-color: #888888FF;
    horizontal-align: 0.50;
    border: none;
}

mainbox {
    children: ["inputbar", "listview"];
    horizontal-align: 0.50;
}

element {
    spacing: 0px;
    margin: 0;
    padding: 4px;
    background-color: transparent;
    text-color: #FEB4CBFF;
    horizontal-align: 0.5;
}

element selected.normal {
	background-color: #0D1117CC;
	text-color: #FEB4CBFF;
    border-radius: 15px;
    border: 3px solid;
    border-color: #FEB4CB;
}

element normal.normal {
	background-color: #0D1117CC;
	text-color: #FEB4CBFF;
}

element alternate.normal {
	background-color: #0D1117CC;
	text-color: #FEB4CBFF;
}

element-text {
    vertical-align: 0.5;
    horizontal-align: 0.5;
}

**Comment by DaveDavenport** [comment]
Can you pastebin the output of `rofi -dump-theme`?

**Reply by jwnome** [reply]
[https://pastebin.com/raw/JDgUyuHQ](url)

**Reply by DaveDavenport** [reply]
```css
message {
    padding:      1px ;
    border-color: var(separatorcolor);
    border:       2px dash 0px 0px ;
}
textbox {
    text-color: var(foreground);
}
listview {
    fixed-height: true;
    padding:      2px 0px 0px ;
    scrollbar:    false;
    cycle:        false;
    lines:        4;
    border-color: var(separatorcolor);
    columns:      1;
    spacing:      0px ;
    border:       2px dash 0px 0px ;
}
scrollbar {
    width:        4px ;
    padding:      0;
    handle-width: 8px ;
    border:       0;
    handle-color: var(normal-foreground);
}
sidebar {
    border-color: var(separatorcolor);
    border:       2px dash 0px 0px ;
}
```
you can see there multiple borders are dashed. 
override these in your theme modifiers to undash them.
