### DISCUSSION TITLE
Is it possible to put the search box/inputbar on the bottom?

### DISCUSSION THREAD

**Discussion by Rabcor** [davatorium/rofi#2054] [Q&A] [answered]
All the themes I've seen the bar is always on top, and I haven't been able to figure out a way to have it on the bottom instead, can it be done?

**Comment by DaveDavenport** [comment, marked as answer]
You can easily change the ordering of packing:

```css
window {
     children: [listview, message, inputbar];
}
```
