### ISSUE TITLE
number of lines does not reflect lines attribute

### ISSUE THREAD

**Issue by OZoneGuy** [davatorium/rofi#1007]
## Version
1.5.4
## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/OZoneGuy/414a6b0255f5edcc07f816b20129dc9f))

## Launch Command
rofi -theme .config/rofi/cusotm_theme.rasi -show drun

## Steps to reproduce

* Step 1 use a custom .rasi, or mine [here](https://gist.github.com/OZoneGuy/9b2acefdde430bed3437738afb32f52c)
* Step 2 launch rofi using the command mentioned above

## What behaviour you see

* - Number of lines shown in listview does not reflect lines attribute in custom_theme.rasi

## What behaviour you expect to see

* - Number of lines in listview to match lines in custom_theme.rasi

**Comment by DaveDavenport** [comment]
This is backwards compatibility..  in the past fullscreen undid the lines setting and sized the number of rows based on the available space.

**Comment by OZoneGuy** [comment]
So, how can I get the lines I want while making rofi cover the whole screen?

Should I use `width: 100%;` and `height: 100%;` instead?

**Comment by DaveDavenport** [comment]
If there is space a widget needs to occupy it. So the trick is to add another widget that occupies the space. (and tell listview not to expand).

modified a theme to show this:
```css
/*
 * ROFI color theme
 *
 * Based on Base16 Material Color Scheme (https://github.com/ntpeters/base16-materialtheme-scheme)
 *
 * User: Tomaszal
 * Copyright: Tomas Zaluckij
 */

* {
	base00: #263238;
	base01: #2E3C43;
	base02: #314549;
	base03: #546E7A;
	base04: #B2CCD6;
	base05: #EEFFFF;
	base06: #EEFFFF;
	base07: #FFFFFF;
	base08: #F07178;
	base09: #F78C6C;
	base0A: #FFCB6B;
	base0B: #C3E88D;
	base0C: #89DDFF;
	base0D: #82AAFF;
	base0E: #C792EA;
	base0F: #FF5370;

	/*base0D: #00BCD4;*/

	spacing: 0;
	background-color: transparent;

	font: "Roboto Mono 13";
}

window {
	transparency: "real";
    fullscreen: true;
	background-color: #263238CC; /*base00 + CC (80% opacity)*/
}

dummy {
    expand: true;
}

mainbox {
	children: [inputbar, message, mode-switcher, listview, dummy];
	spacing: 30px;
	/*margin: 20%;*/
	padding: 30px 0;
	border: 1px;
	border-color: @base0D;
}

inputbar {
	padding: 0 30px;
	children: [prompt, textbox-prompt-colon, entry, case-indicator];
}

prompt {
	text-color: @base0D;
}

textbox-prompt-colon {
	expand: false;
	str: ":";
	margin: 0 1ch 0 0;
	text-color: @base0D;
}

entry {
	text-color: @base07;
}

case-indicator {
	text-color: @base0F;
}

sidebar, message {
	border: 1px 0;
	border-color: @base0D;
}

button, textbox {
	background-color: @base03;
	text-color: @base07;
	padding: 5px;
}

button selected {
	background-color: @base0D;
}

listview {
	scrollbar: true;
	margin: 0 10px 0 30px;
    expand: false;
lines: 5;
}

scrollbar {
	background-color: @base03;
	handle-color: @base0D;
	handle-width: 10px;
	border: 0 1px;
	border-color: @base0D;
	margin: 0 0 0 20px;
}

element {
	padding: 5px;
	highlight: bold underline;
}

element normal {
	background-color: transparent;
}

element selected {
	background-color: @base0D;
}

element alternate {
	/*background-color: @base03;*/
}

element normal normal, element selected normal, element alternate normal {
	text-color: @base07;
}

element normal urgent, element selected urgent, element alternate urgent {
	text-color: @base0F;
}

element normal active, element selected active, element alternate active {
	text-color: @base0B;
}
```
