### ISSUE TITLE
Center Entry field

### ISSUE THREAD

**Issue by mustaqimM** [davatorium/rofi#1038]
How do I centre the prompt input field?

![2019-12-12_07-50](https://user-images.githubusercontent.com/24436622/70686196-6e0fd600-1ca3-11ea-9999-99ec694c7a83.png)

I tried setting as `text-align: center !important;`, but that doesn't work. So now I have it set as
```css
entry {
  padding: 0px 0px 0px 280px; }
```
