### ISSUE TITLE
[REQUEST] Hide listview until user has typed

### ISSUE THREAD

**Issue by rcarriga** [davatorium/rofi#1079]
On initial startup the listview can be a bit noisy. It would be great if there was an option to only show elements once the user has typed something (i.e. Filter out all elements if input is empty).

An option like this would work
```css
#listview {
    require-input: true;
}
```
but that is just off the top of my head.

- Rofi version: 1.5.4
