### ISSUE TITLE
Adding margin to icons not working

### ISSUE THREAD

**Issue by CollinAlpert** [davatorium/rofi#1129]
When adding a margin to the icon in an element, it doesn't seem to get applied. Here's my styling:
```css
* {
  background-color: #282C33;
  border-color: #2e343f;
  text-color: #8ca0aa;
  spacing: 0;
  width: 512px;
  border-radius: 5px;
}

window {
  border: 1px;
  border-color: #36384A;
}

inputbar {
  border: 0 0 1px 0;
  children: [prompt,entry];
}

prompt {
  padding: 16px;
  border: 0 1px 0 0;
}

textbox {
  background-color: #2e343f;
  border: 0 0 1px 0;
  border-color: #282C33;
  padding: 8px 16px;
}

entry {
  padding: 16px;
}

listview {
  cycle: false;
  margin: 0 0 -1px 0;
  scrollbar: false;
}

element {
  border: 0 0 1px 0;
  padding: 16px;
}

element selected {
  background-color: #2e343f;
}

element-icon {
  margin: 0 10px 0 0;
}
```

The critical part should be 
```css
element-icon {
  margin: 0 10px 0 0;
}
```

Anything I am doing wrong? I am trying to get some space between the text and the icon.
I am running Fedora 32 with Kernel 5.6.12-300.fc32.x86_64 and Rofi version 1.5.4.
