### ISSUE TITLE
[REQUEST] Add the ability to nest @media queries

### ISSUE THREAD

**Issue by vahnrr** [davatorium/rofi#1189]
**Describe the feature**
- Nesting `@media` queries would allow to re-use style
- It would look like:

``` css
@media (min-width: 500px) {
  @media (min-width: 767px) {
    * {
      width-specific-color: #ff0000;
    }
  }
  @media (min-width: 1079px) {
    * {
      width-specific-color: #00ff00;
    }
  }
  window {
    background-color: @width-specific-color;
    color: #000000;
  }
};
```

**When reporting a feature request include the following information:**
- Rofi version: `Version: 1.6.0-6-g3b86326b (makepkg)`
