### ISSUE TITLE
[BUG] Different font (size) in input and listview does not work (after 1.6.0)

### ISSUE THREAD

**Issue by klorax** [davatorium/rofi#1247]
## Version

Version: 1.6.1

## Configuration

Default (except `test.rasi` theme, see below), i.e., no `config.rasi`.

## Launch Command

`rofi -theme test -show run`

## Steps to reproduce

- Create the example theme `test.rasi` below.
- Run `rofi`.

`test.rasi`:
```css
window {
    font:                        "Exo 32px";
}

element-text {
    font:                        "Monospace 15px";
}
```

## What behaviour you see

- All line heights are the same (too large in this case for the _listview_).

![actual](https://user-images.githubusercontent.com/31596164/103178700-6ce92100-4885-11eb-99e1-2c84f2500c27.png)

## What behaviour you expect to see

- Line heights adapted based on font (size).

![expected](https://user-images.githubusercontent.com/31596164/103178708-812d1e00-4885-11eb-91ef-9856cdde3f7f.png)

**Additional details:**
- In earlier versions this was possible, perhaps this was not intended.
- If intended, then the fix for https://github.com/davatorium/rofi/issues/1190 might have caused this bug.
- If not intended, then please consider this a feature request.
