### ISSUE TITLE
[BUG] Dashed border feature doesn't appear to work

### ISSUE THREAD

**Issue by adrian5** [davatorium/rofi#1264]
## Version

1.6.1

## Configuration
```markdown
Detected modi:
    * window
    * windowed
    * run
    * ssh
    * drun
    * +combi
    * keys
    * file-browser

Compile time options:
    * window enabled
    * drun enabled
    * gcov disabled
    * asan disabled
```
#### config.rasi

```css
configuration {
  modi: "combi";
  combi-modi: "drun,window";
  terminal: "termite";
  theme: "test-theme";
  lines: 5;
  fixed-num-lines: false;
  display-combi: "? ";
  display-drun: "r";
  display-window: "w";
}
```

#### test-theme.rasi

```css
#inputbar {
  border: 2px dash;
}
```

## Launch Command

```shell
rofi -show combi
# i3: exec --no-startup-id rofi -show -combi
```

## Steps to reproduce

Invoke rofi.

## What behaviour you see

Any border is displayed as a solid line, instead of "dashed". It looks identical with `border: 2px solid;` and `border: 2px;`.

## What behaviour you expect to see

I was trying to replicate the look seen in e.g. the [Adapta-Nokto](https://github.com/davatorium/rofi-themes/tree/master/Official%20Themes#adapta-nokto) theme.
