### ISSUE TITLE
If you have issues with themes going to version 1.7.0 or up please read this!

### ISSUE THREAD

**Issue by DaveDavenport** [davatorium/rofi#1397]
If you have issues with theming in 1.7.0 please read [release notes](https://github.com/davatorium/rofi/releases/tag/1.7.0) and use [discussion forum](https://github.com/davatorium/rofi/discussions/categories/theming) for questions. 

If you found a theming bug, we will move it from the discussion to the issue tracker as bug.

**Comment by DaveDavenport** [comment]
From the release notes:

An old pre-1.6.1 rasi theme should work with the following section added:
```css
element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}
```
