### ISSUE TITLE
[REQUEST] Move selection to best match when refining search

### ISSUE THREAD

**Issue by bew** [davatorium/rofi#1405]
## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented
- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

When I search for something I type a few chars, then I might scroll down, see the results I currently have, then want to refine my search and add more chars.
The selection currently stays where it was before adding more chars.

I'd like to have the selection always go to the top, to be on the current best match.

Other software with this behavior: fzf, with its `change:top` binding.

## How do you know that this problem exists today? Why is this important?

It's important to me to have seamless search behavior, so I can quickly search / refine / search / refine / ... and find what I want.

Also, I don't see how the current behavior can be useful for anything..

## Who will benefit from it?

... me, people like me who want to be efficient ...

## Version

Output of `rofi -v`: `Version: 1.7.0`

## Configuration

Output of `rofi -help`: https://gist.github.com/bew/453457c12d439dc6910ad93522778c90

**Comment by DaveDavenport** [comment]
I've added an initial implementation on a branch (i1405)
I am not fully convinced about hte naming of the option:

```bash
    rofi -show drun -inputchange-movetop true
```
    
or
    
```css
    configuration {
            inputchange {
                    movetop: true;
            }
    }
```

other actions we might want to do on input-change?

**Comment by DaveDavenport** [comment]
changed it to be able to bind keys.. (yes you can create problems this way):

```css
configuration {
    inputchange {
        action: "kb-row-first";
    }
}
```

this is similar to the timeout option.
