### ISSUE TITLE
[BUG] Performance issue with hover-select in high resolution screen

### ISSUE THREAD

**Issue by xlucn** [davatorium/rofi#1423]
### Rofi version (rofi -v)

Version: 1.7.0

### Configuration

https://gist.github.com/OliverLew/8439b88b260113699177df0e256e8cfd

### Launch command

rofi -show drun

### Step to reproduce

- start rofi by `rofi -show drun` with the configuration
- scroll to second page
- move the cursor in a large circle
- see the issue

### Expected behavior

The selection highlight follows the cursor closely

### Actual behavior

There is a great lagging, see the screencast:

https://user-images.githubusercontent.com/12032219/131952251-a188e94a-9d87-48cc-83b0-6dc500d3c924.mp4

### Additional information

Conditions:
- (Edit: Second page. This does not happen in the first page.)
- High resolution. (Edit: My current resolution is 2880x1800.) I tried to use xrandr to change the resolution to 1920x1200, the lagging is much smaller.
- Many icons. If I change the lines and columns to show less (<20) icons, the lagging will be much smaller.
- Large icons. if I change the element-icon to be smaller, the lagging will be much smaller.

This is my MWE `config.rasi`, I used this to dump the full configuration in the gist above
```css
configuration {
    modi: "drun";
    show-icons: true;
    hover-select: true;
}

window {
    width: 100%;
    height: 100%;
}

listview {
    columns: 7;
    lines:   5;
}

element {
    padding: 4%;
}

element-icon {
    size: 10%;
}
```
