### ISSUE TITLE
[BUG] Follow up on nested @media queries (#1189)

### ISSUE THREAD

**Issue by vahnrr** [davatorium/rofi#1442]
### Rofi version (rofi -v)

Version: 1.7.0

### Configuration

https://gist.github.com/vahnrr/bc0820940e3c0e6f890e16b52fc6a169

### Launch command

echo 'q;w;e;r;t;y' | rofi -dmenu -sep ';'

### Step to reproduce

- Have a 1920x1080 display
- Define a `background-color` for any widget
- Set a different value for it in a nested `@media` query that shouldn't be matched, such as:
```css
/* This nested query is supposed to match a 1080x1920 display while rofi is started on a 1920x1080 display. */
@media ( min-width: 1080 px ) { /* true */
  @media ( max-width: 1081 px ) { /* false */
    @media ( min-height: 1920 px ) { /* false */
      @media ( max-height: 1921 px ) { /* true */
        listview {
          background-color: rgba ( 255, 0, 0, 100 % );
        }
      }
    }
  }
}
```

### Expected behavior

Since the second query fails, the rest of the nested queries should be ignored.

### Actual behavior

The second `@media` query fails but that doesn't stop the theme from applying the configuration of the fourth query.

### Additional information

The version of rofi used is built from this [release](https://github.com/davatorium/rofi/releases/tag/1.7.0).

After some tinkering, I found that when the 1920x1080 display is focused, the 1080x1920 theming is applied but then overriden by the nested queries from 1920x1080.
However, if 1080x1920 is focused, then the 1920x1080 queries will be ignored.
I assume this is due to the fact that 1920x1080's fourth query is correct for 1080x1920, but 1080x1920's fourth query isn't correct for 1920x1080.
But since prior queries fail, the fourth one shouldn't be reached.

As implied by the configuration I'm trying to build, I have 2 monitors: 1080x1920 and 1920x1080. I can confirm that the faulty behaviour happens when both are plugged-in but also when only the 1920x1080 is.

Also, in #1189 the intent was to set a variable in a nested `@media` query, and then use it in rest of the theming, but it seems like such a variable is limited to the query's scope.

**Comment by DaveDavenport** [comment]
This is a very untested feature, as I implemented it and I never got any feedback (see linked issue).

For me your above one shows red on full hd screen but not on 4k monitor, but Ill try to reproduce your exact use-case later.

**Comment by DaveDavenport** [comment]
can you try the i1442 branch to see if this fixes it?

**Comment by vahnrr** [comment]
I am really sorry for not following up on the original issue at the time...

Your commit fixed the nesting problem, when a query fails its children are ignored, well done!

Also, do you think the variable override in a nested query not working outside its scope is intended?

**Comment by DaveDavenport** [comment]
What exactly do you mean with this:

```
Also, do you think the variable override in a nested query not working outside its scope is intended?
```

(how it currently works is,, after loading the theme, it does a run where it flattens all the media () down into the root level (so everything inside the media is then merged into the parent).

So inside a media in the end takes precedence over statements outside  media that are declared afterward.
I must admit I ddi not consider this.)

**Comment by vahnrr** [comment]
```css
* {
  --padding: 100px;
}

/* Intent: override the default padding if the resolution matches a specific value. */
@media(min-width: 1920px) {
  @media(max-width: 1921px) {
    * {
      --padding: 200px;
    }
  }
}

window {
  padding: var(--padding);
}
```

This is what I'm trying to make, however the `--padding` variable isn't changed inside a `@media` query. My understanding after testing a few different approaches is that any `* { ... }` within a `@media` query is ignored.

For example this alone changes the colour:
```css
* {
  background-color: #f00;
}
```

But this doesn't:
```css
@media(min-width: 1920px) {
  @media(max-width: 1921px) {
    * {
      background-color: #f00;
    }
  }
}
```

**Comment by DaveDavenport** [comment]
Thanks for explaining, that was intended to work :D

**Comment by vahnrr** [comment]
I see, thanks for confirming this and for the great work you put into rofi!

**Comment by DaveDavenport** [comment]
added a commit that should fix the above example with `*{} `  in a media.

I've added `-dump-processed-theme`  as a test that prints the theme after processing. (so launch it on monitor you want to check).

**Comment by DaveDavenport** [comment]
Can you test?

**Comment by vahnrr** [comment]
I can't seem to find the output from `-dump-processed-theme` from stdout.
However, the commit sure did add the behaviour I was after.

**Comment by DaveDavenport** [comment]
Weird,  `rofi -dump-processed-theme`  should output the theme on a terminal.

```css
rofi -dump-processed-theme -no-default-config
/**
 * rofi -dump-theme output.
 * Rofi version: 1.7.0-dev
 **/
* {
    mycolor: rgba ( 255, 0, 0, 100 % );
}
listview {
    background-color: var( mycolor, rgba ( 0, 0, 255, 100 % ));
}
test {
    aap: rgba ( 0, 0, 255, 100 % );
}
```
