### ISSUE TITLE
[BUG] Theme overrides not applied when set in config.rasi

### ISSUE THREAD

**Issue by knovoselic** [davatorium/rofi#1468]
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/knovoselic/e1309ac77ae8cff01b46be2f49128690

### Launch command

`rofi -show drun -modi drun`

### Step to reproduce

Add this to your `config.rasi` file.
```
configuration {
        theme: "gruvbox-dark";
        combi-modi: "drun";
        show-icons: true;
}

window {
  width: 800px;
  height: 400px;
}

element-icon {
  size: 4ch;
}
```

Run rofi using `rofi -show drun -modi drun`.

### Expected behavior

Theme overrides/styling from `config.rasi` are applied.

### Actual behavior

Theme overrides/styling from `config.rasi` are completely ignored.

![image](https://user-images.githubusercontent.com/7026420/134147504-bc5d4e0c-c95f-435b-9aa3-527af8b08bfc.png)

### Additional information

Theme overrides/styling from `config.rasi` work fine if I remove `theme` field from the `configuration` block.

**Comment by DaveDavenport** [comment]
(See also  the discussion [forum](https://github.com/davatorium/rofi/discussions/1436#discussioncomment-1287951) and manpages).

The following option:
```css
configuration {
theme: "theme";
}
```
should have been removed. This was a mistake on my side. apologies.

Please use:

```css
configuration {
      
        combi-modi: "drun";
        show-icons: true;
}
@theme "gruvbox-dark"
window {
  width: 800px;
  height: 400px;
}

element-icon {
  size: 4ch;
}

```
