### ISSUE TITLE
[BUG] dpi calculation error on rotated displays (wayland)

### ISSUE THREAD

**Issue by ghost** [davatorium/rofi#1590]
### Rofi version (rofi -v)

1.7.3

### Configuration

https://gist.github.com/qodo-io/36623f90c03ae96204b0d9d1748102e7

### Launch command

rofi --help

### prerequisites:
-  rotated wayland display (i.e.`swaymsg output DP-1 transform 90`)
_optional_: physically rotate your display to get your neck into a healthy debugging position)

### steps: 
- run `rofi --help` and identify the `Monitor layout:` section
- _optional_: filter the output to see it immediatelty: 
```bash
rofi --help | sed -r -e '/^\s*(ID:|name:|position:|size:|size:)/!d;s/^\s*/  /;s/  ID: ([0-9]*$)/\1:/;s/dpi:/\n  dpi:/;s/size: ([0-9]*),([0-9]*)/width: \1\n  height: \2/;s/position: ([0-9]*),([0-9]*)/x: \1\n  y: \2/'
``` 

### Expected behavior

```yml
0:
  name: XWAYLAND15
  x: 3840
  y: 0
  width: 1440
  height: 2560
  size: 530mm,300mm  
  dpi: 123,123             # <-------- correct
```
correct dpi would be `123,123` in this example, as:

```fish
 ~   calc                                                                                                                                                                      
   precision: e^-8
   2560/(53/2.54)
   2560/(53/2.54):  122.68679246
```

### Actual behavior

```yml
0:
  name: XWAYLAND15
  x: 3840
  y: 0
  width: 1440
  height: 2560
  size: 530mm,300mm  
  dpi: 69,217             # <-------- incorrect
```
dpi is `69,217`, as `width` and `height` are flipped
```
 ~   calc                                                                                                                                                                      
   precision: e^-8
   1440/(53/2.54):  69.01132076
   2560/(30/2.54):  216.74666670
```

### Additional information

**probable root cause:** the dpi calculation does not take wayland display rotation into account (sway example from CLI: ` swaymsg -t get_outputs | jq '.[]|.transform'`)
