### ISSUE TITLE
[Bug] Breaks with a custom theme

### ISSUE THREAD

**Issue by RaptaG** [davatorium/rofi#1657]
### Rofi version (rofi -v)

1.7.3

### Configuration

I used [this YouTube tutoral](https://www.youtube.com/watch?v=uvvoJU69uNo)

### Launch command

^

### Step to reproduce

Follow the tutorial provided above

### Expected behavior

It should look like this:
https://youtu.be/uvvoJU69uNo?t=1217

### Actual behavior

It looks like this:
![image](https://user-images.githubusercontent.com/77157639/179245317-43684282-dec6-427f-b1d3-6b71b0b44f0b.png)

### Additional information

Screen resolution 1366x768

**Comment by DaveDavenport** [comment]
Please provide the requested information

**Comment by RaptaG** [comment]
> Please provide the requested information

Could please guide me? What information _is_ missing?

**Comment by DaveDavenport** [comment]
The ones asked for when creating the issue.
If I have the configs I can test things,  now I cannot.

**Comment by RaptaG** [comment]
> The ones asked for when creating the issue. If I have the configs I can test things, now I cannot.

Ok then, here you are:
https://gist.github.com/RaptaG/c7f4cc29e32db24541e11592761ce9e4

**Comment by DaveDavenport** [comment]
That is still missing some of the requested information, but enough for me to see that this is not a bug.
That theme is outdated and has broken internal links.  I did a quick fix:

```css
/*
 *
 * Author  : Aditya Shakya
 * Mail    : adi1090x@gmail.com
 * Github  : @adi1090x
 * Twitter : @adi1090x
 *
 */

configuration {
	font:							"Noto Sans Bold 10";
    show-icons:                     true;
	icon-theme: 					"WhiteSur-dark";
    display-drun: 					"";
    drun-display-format:            "{name}";
    disable-history:                false;
    fullscreen:                     true;
	hide-scrollbar: 				true;
	sidebar-mode: 					false;
}

* {
    background:                     #00000060;
    background-alt:              	#00000000;
    background-bar:                 #f2f2f215;
    foreground:                     #f2f2f2EE;
    accent:			            	#ffffff66;
}

window {
    transparency:                   "real";
    background-color:               @background;
    text-color:                     @foreground;
	border:							0px;
	//border-color:					@border;
    border-radius:                  0px;
    fullscreen: true;
}

prompt {
    enabled: 						true;
	padding: 						0.30% 1% 0% -0.5%;
	background-color: 				@background-alt;
	text-color: 					@foreground;
	font:							"FantasqueSansMono Nerd Font 12";
}

entry {
    background-color:               @background-alt;
    text-color:                     @foreground;
    placeholder-color:              @foreground;
    expand:                         true;
    horizontal-align:               0;
    placeholder:                    "Search";
    padding:                        0.10% 0% 0% 0%;
    blink:                          true;
}

inputbar {
	children: 						[ prompt, entry ];
    background-color:               @background-bar;
    text-color:                     @foreground;
    expand:                         false;
	border:							0.1%;
    border-radius:                  6px;
	border-color:					@accent;
    margin:                         0% 30% 0% 30%;
    padding:                        1%;
}

listview {
  expand: true;
    background-color:               @background-alt;
    columns:                        8;
    lines:                          4;
    spacing:                        2%;
    cycle:                          false;
    dynamic:                        true;
    layout:                         vertical;
}

mainbox {
    background-color:               @background-alt;
	border:							0% 0% 0% 0%;
    border-radius:                  0% 0% 0% 0%;
	border-color:					@accent;
    children:                       [ inputbar, listview ];
    spacing:                       	8%;
    padding:                        10% 8.5% 10% 8.5%;
}

element {
    background-color:               @background-alt;
    text-color:                     @foreground;
    orientation:                    vertical;
    border-radius:                  0%;
    padding:                        2.5% 0% 2.5% 0%;
}

element-icon {
    size:                           52px;
    border:                         0px;
}

element-text {
    expand:                         true;
    horizontal-align:               0.5;
    vertical-align:                 0.5;
    margin:                         0.5% 0.5% -0.5% 0.5%;
}

element selected {
    background-color:               @background-bar;
    text-color:                     @foreground;
	border:							0% 0% 0% 0%;
    border-radius:                  12px;
    border-color:                  	@accent;
}
element-text, element-icon {
    background-color: transparent;
    text-color:       inherit;
}
```
