### ISSUE TITLE
[BUG] element does not support textbox children

### ISSUE THREAD

**Issue by friedow** [davatorium/rofi#1817]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/friedow/b7f5504d73fb24a5debf469009429e12

### Theme

https://gist.github.com/friedow/b7f5504d73fb24a5debf469009429e12

### Launch command

rofi -show drun

### Step to reproduce

1. Create a theme containing
``` rasi
* {
    // font: "monospace 12";
    background-color: black;
    text-color: white;
}

element {
    children: [ element-text, textbox-foo ];
}

textbox-foo {
    content: "foo";
    background-color: green;
}
```
1. Launch rofi with `rofi -show drun`
1. This should produce a rofi screen with green boxes without content:
![image](https://user-images.githubusercontent.com/17351844/221599174-38822303-2827-4a2d-bb48-355245546d5c.png)

### Expected behavior

The green boxes should contain the string `foo`.

### Actual behavior

The green boxes contain nothing.

### Additional information

I would love to fix that myself if you dont mind. I think I already found the correct place to fix this. You can expect a pull request for this in the next few days :).

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

**Comment by DaveDavenport** [comment]
https://github.com/davatorium/rofi/pull/1792

This fixes adding any widget to the listview, it just waits for a documentation update (to explain the change it makes).

**Comment by DaveDavenport** [comment]
btw your example already works, except you have no space assigned to textbox-foo

```css
* {
    // font: "monospace 12";
    background-color: black;
    text-color: white;
}

element {
    children: [ element-text, textbox-foo ];
}

textbox-foo {
    content: "foo";
    background-color: green;
    expand: true;
}
```
